---
- include_vars:
    file: "{{ ansible_distribution }}.yml"
    name: os_vars

- name: Git packages install
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ os_vars.git_required_packages }}"
