---
- name: create user accounts for all our servers
  hosts: web1.example.com
  become: true
  remote_user: ansible
  vars_files:
    - secret.yml
  tasks:
    - name: Creating user from secret.yml
      user:
        name: "{{ username }}"
        password: "{{ pwhash }}"