---
# 1) 방화벽 서비스 OFF - http(80/tcp), https(443/tcp) => firewalld
# 2) 서비스 OFF - httpd => service
# 3) 서비스 설정 삭제 - /var/www/html/index.html => file
# 4) 패키지 삭제 - httpd, mod_ssl => yum

- name: "인트라넷 웹서버 설정 복원 작업"
  hosts: web1
  tasks: 
  - name: Disable service - http(80/tcp), https(443/tcp)
    firewalld:
      port: "{{ item  }}"
      permanent: yes
      immediate: yes
      state: disabled
    loop:
      - 80/tcp
      - 443/tcp

  - name: "(2) 서비스 OFF - httpd => service"
    service: 
      name: httpd
      state: stopped
      enabled: no
    ignore_errors: yes
    
  - name: "(3) 서비스 설정 삭제 - /var/www/html/index.html"
    file:
      path: /var/www/html/'index.html'
      state: absent

  - name: "(4) 패키지 삭제 - httpd, mod_ssl => yum"
    yum:
      name: 
        - httpd
        - mod_ssl
      state: absent