---
- name: DB 설치
  hosts: database_dev
  tasks:
  - name: 패키지 설치
    yum:
      name: "{{ pkg_db }}"
      state: lastest
    vars:
        - mariadb-server
        - python3-PyMySQL
      when: ansible_distribution == 'CentOS'

  - name: 서비스 기동
    service:
      name: mariadb
      state: starte
      enabled: yes
      
      

     # yum:
    #   name: "{{ item }}"
    #   state: latest
    # loop: "{{ pkg_db }}"
    # vars:
    #   pkg_db: 
    #   - mariadb-server
    #   - python3-PyMySQL
    # yum -y install mariadb-server python3-PyMySQL